package eu.mikko.intervaltraining.entities

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(tableName = "training_notifications_table", indices = [Index(value = ["dayOfWeek"], unique = true)])
data class TrainingNotificationEntity(
    //Does not really matter if it is autogenerated
    @PrimaryKey(autoGenerate = false) val id: Int,
    val dayOfWeek: String,
    val time: String,
    val isEnabled: Boolean)